version: '3'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    container_name: mariadb
    hostname: mariadb
    env_file:
      - ./mariadb.env
    volumes:
      - ./database/mysql/data:/var/lib/mysql:rw
      - ./technical_test.sql:/docker-entrypoint-initdb.d/schema.sql:ro

  laravel:
    image: docker.io/bitnami/laravel:9
    container_name: laravel
    hostname: laravel
    ports:
      - '8000:8000'
    env_file:
      - ./laravel.env
    volumes:
      - './trusmedika-rs:/app'
    depends_on:
      - mariadb
